### ISSUE TITLE
بعضی از لینکا رو نداره

### ISSUE THREAD

**Issue by SafaSafari** [SamadiPour/iran-hosted-domains#11]
درود بر تو عزیز

sut.ac.ir
pada.medu.ir
sida.medu.ir
ltms.medu.ir
و خیلی از لینکای دیگه مخصوصا روی medu.ir :))

**Comment by SamadiPour** [comment]
سلام.
دامنه های موجود اکثرا از سایت وزارت ارتباطات و مربوط به لیست دامنه های اینترنتی با میزبانی داخلی ثبت شده هستش.
به همین دلیل ممکنه که بعضی از دامنه های مد نظر وجود نداشته باشد.

حالا نکات دیگه:
۱- اگر از کانفیگ برنامه ها استفاده کنید نیازی به دامنه های ایران نیست. به این جهت که تمام دامنه های 
ir
رو شامل میشه و لازم نیست تک تک اضافه کنید.

۲- اگر از فایل
iran.dat
استفاده میکنید باز هم به دامنه های جانبی سایت
medu
نیاز نیست چون خود دامنه اصلی وجود داره و بقیه رو شامل میشه
![image](https://user-images.githubusercontent.com/24422125/124380593-be5de700-dcd2-11eb-9ca6-becfe6b454ea.png)

۳- از اونجایی که دامنه
sut.ac.ir
وجود نداره من در لیست به صورت دستی وارد میکنم.

ممنون از توجهتون.

**Comment by SafaSafari** [comment]
دمت گرم عزیز
با توحه به نکته 2
اگه
ac.ir
رو اضافه کنی، تمام دانشگاه های کشور رو شامل میشه
:)
❤️

**Comment by SafaSafari** [comment]
یه پیشنهاد دیگه هم دارم :))
برنامه
netch
رو حتما دیدین
:)
ip
همین دامین ها رو دربیارین و داخل فایل
bypass
قرار بدید
:)
