### ISSUE TITLE
Waze & sagernet

### ISSUE THREAD

**Issue by Apanj** [SamadiPour/iran-hosted-domains#12]
سلام 
امروز به نکته جالب بر خوردم ، زمانی که در ساگرنت 
Iran.Dat:other و Iran.Dat:ads 
را روشن و در حالت بای‌پس و بلاک قرار میدهم ارتباط برنامه ویز با شبکه قطع میشود

**Comment by SamadiPour** [comment]
سلام
اگر ممکنه لطفا دقیق‌تر بررسی کنید. اول ببینید کدوم یکی از اون دو مورد به تنهایی باعث این مشکل میشوند!
دوم این که چک کنید اپلیکیشن و سایت ویز هر دو قطع میشوند یا خیر.

**Comment by Apanj** [comment]
جناب صمد پور 
هر یک به تنهایی یا هر دو با هم این مشکل را بوجود می‌آورند . این مشکل فقط در نرم افزار ویز وجود دارد و اختلالی در سایت ایجاد نمیکند
