### ISSUE TITLE
وی پی ان

### ISSUE THREAD

**Issue by realartin** [SamadiPour/iran-hosted-domains#16]
درود خسته نباشید / امکانش هست که بشه این متد رو روی فیلترشکن هایی مثل نورد اجرا کرد ؟

**Comment by SamadiPour** [comment]
یک سری کار ها میشه کرد ولی راحت نیست و من هنوز انجامش ندادم. برای مثل:
- از آی‌پی تیبل لینوکس استفاده کنید
- برای مک از اسکریپت زیر استفاده کنید و دامنه های مورد نیاز رو بای‌پس کنید
https://gist.github.com/abedinpour/53cda88effbd997e2e271ae48cf9c143

- کانفیگ اوپن‌وی‌پی‌ان نورد رو بگیرید و فایل کانفیگ رو تغییر بدید که دامنه هارو بای‌پس کنه
https://www.youtube.com/watch?v=SEA2T_ZXJ9w

به صورت مستقیم خود فیلترشکن ها این قابلیت رو ندارند.

**Comment by realartin** [comment]
اون اسکریپت که برای مک گذاشتید امکانش هست برای ویندوز هم مشابه اش باشه ؟ / بعد درمورد اون اسکپریت مهم نیست فیلترشکن چی باشه ؟ کانفیگ اوپن وی پی ان نورد رو چطور میتونم تهیه کنم ، ممنون بابت زحماتی که می کشید

**Comment by SamadiPour** [comment]
امکانش شاید باشه ولی من اطلاعی ندارم. اسکریپت برای کل سیستم استفاده میشه و فیلترشکن مهم نیست.

کانفیگ رو از آدرس زیر میشه گرفت:
https://nordvpn.com/ovpn/
