### ISSUE TITLE
range ip

### ISSUE THREAD

**Issue by realartin** [SamadiPour/iran-hosted-domains#18]
درود ی سوال ذهن من رو مشغول کرده ، چرا به جای اضافه کردن تکی ایپی ها از رنج ایپی استفاده نمیکنید مثلا از رنج 
xxx.xxx.xxx تا xxy.yyy.yyy 
برای ایرانه فقط خب چرا این هارو کلی اضافه نمیکنید ؟

**Comment by realartin** [comment]
اینطور باید هردفه دستی چک کنید ، فکر هم نمیکنم سایتی ک برای دریافت ایپی ازش استفاده میکنید 
api 
هم داشته باشه و هردفعه باید دستی چک کنید ...

**Comment by SamadiPour** [comment]
سلام.
بنده هیچ موردی رو دستی چک نمیکنم و تمام پروسه خودکار هستش.
هیچ تک آی‌پی ای استفاده نمیشه. دامنه هستن.
برای آی‌پی میشه از
geoip
استفاده کرد.
