### ISSUE TITLE
May you please add these domains to ads list

### ISSUE THREAD

**Issue by rustforfuture** [SamadiPour/iran-hosted-domains#20]
سلام
لطفا درصورت امکان این دامنه ها رو هم توی لیست تبلیغات تون قرار بدین

چند تا دامین (خیلی کم) ممکنه تکراری باشه با لیستتون ولی متاسفانه به خاطر مشکل چشمی که دارم و ابزار اتوماتیک برای چک کردنش نداشتم نتونستم از لیست پیشنهادیم غربالشون کنم

در آخر خیلی ممنون از لیست هاتون
موفق و پاینده باشید

نت بینا دات کام رو دارین توی لیستتون ولی دات نت رو خیر
netbina.net

appsharj.com
api.appsharj.com

api.sanjagh.com
sanjagh.com
sanjagh.net

fastclick.click
fastclick.co

kaprila.com
landyab.com
tavoos.net
iranwebads.com
merita.ir
mihanclick.info
networksara.com
nextads.ir
popland.info
utop.ir
vatanclick.ir
weclick.ir
ad2ad.ir
adnegah.net
adsima.net
adpulse.ir
adtube.ir
clickyab.com
iprank.ir
impressions.ir
ipopup.ir
ipsell.ir
popupads.ir
irclick.net
persianrank.ir

persianstat.com
persianstat.ir

metrix.ir
analytics.metrix.ir

api.tapsell.ir
najva.com

adad.ir
s.adad.ir

با تشکر فراوان

**Comment by rustforfuture** [comment]
در ضمن لیستی برای کم کردن فیشینگ شاپرک هم داشتم 
اگر دوست داشتین توی لیست 
تبلیغاتتون ازش استفاده کنین
این لیست رو دستی نوشتم ولی خب اکثر تاپ لول دامین هایی که توی ایران رایج هستن رو فکرکنم پوشش بده
تاپ لول دامین دیگه ای به ذهنم نرسید اد کنم به لیست

shaaparak.net
shaaparak.in
shaaparak ir
shaaparak.biz
shaaparak.io
shaaparak.tk
shaaparak.info
shaparak.info
shaaparak.com
shaparak.biz
shaparak.io
shaparak.in
shaparak.tk
shaparak.net
shaparak.com
shaaparak.ir
shaparak.cf
shaaparak.cf
shaparak.site
shaaparak.site
shaparak.us
shaaparak.us

با تشکر فراوان

**Comment by rustforfuture** [comment]
ببخشید اشتباه دستم خورد

لطفا این دامنه رو هم اضافه کنین
به لیست بالا هم با اذیت اضافه اش کردم

**Comment by SamadiPour** [comment]
سلام.
منبع این دامنه ها کجاست؟
من نمیتونم تک تک چک کنم و مطمئن بشم که تمام این موارد دامنه تبلیغاتی هستش یا نه.
درضمن حتما چک کنید که تو لیست نباشن.
منم ابزار خودکاری ندارم

**Comment by rustforfuture** [comment]
به حز دو مورد که یکیش ردگیر داخلی یه نرم افزار خاص بود که روی دامنه خودش سازنده اش پیاده کرده بود و یک مورد که خارجی بود و جفتشون رو الان توی چک کردنم پاک‌کردم بقیه سرویس های کلیکی، آمارگیر، بالاربردن رنک سایت توی الکسا با روش های سو استفاده از یوزر و... هستن

مثلا کاپریلا هم سرویس نشون دادن مطالب مرتبط تبلیغاتی با هوش مصنوعی هست 

البته نزدیک ۵ -۶ تاشون یا لود نشدن یا دامنشون اکسپایر شده بود

این آدرس ها رو توی لاگ نرم افزار ادبلاکر براساس دی ان اس خودم پیداشون کردم طی چندماه چک‌کردن لاگ در پارسال

سعی میکنم روشی برای خودکار پاک کردن اضافی ها پیدا کنم و لیست غربال شده رو تحویلتون بدم

البته ممکنه هر کدوم از از اینها چند سابدامنه داشته باشن به همین دلیل ممکنه کامل ردیاب هاشون بلاک نشه اگر الگوریتم های ساگرنت و...سابدامین های یه لیست رو بلاک نمیکنه

ولی خب حداقل بهتر از این هستن که کلا نباشن باز هرطور صلاح میدونین

اگر مشکل چشم نداشتم خودم یه لیست درسا میکردم و لیست جنابعالی و دامنه های کلیکی از لیست های ایرانی دیگه رو هم توش میگذاشتم که برای ادبلاکر های دی ان اس بیس مناسب باشه و یک جا یک لیست از چند سورس باشه ولی متاسفانه مشکل چشمم باعث شده همین متن رو هم با کلی مشکل و پماد و... بنویسم برای شما

با تشکر

**Comment by rustforfuture** [comment]
این شهص اسکریپت هایی که برای حذف موارد تکراری استفاده میکنه رو به اشتراک گذاشته

اگر دوست داشتین یه نگاه بهشون بندازین شاید کمکتون کنن کلا در این کار

(پیشنهاد کلی بود واگرنه لیست بالا رو سعی میکنم خودم تکراری هاش رو حذف کنم و اینجا بفرستم دوباره)

**Comment by rustforfuture** [comment]
سلام 
شرمنده به علت تاخیر
فعلا به دلیل شدت مشکل چشم نتونستم تکراری ها رو چک کنم

اگر میخواهید ایشو رو ببندم و وقتی دامنه ها رو غربال کردم دوباره بازش کنم؟

**Comment by Muhammadsalihy** [comment]
Soft98.ir
P30download.ir
Salamdl.life
این دومین ها را هم لطف نماید

**Comment by MasterKia** [comment]
@rustforfuture @Muhammadsalihy 

میتونید لیست PersianBlockerHosts رو به مسدودساز DNS ای که دارید اضافه کنید تا تبلیغات مسدود بشن:
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt

اگر هم افزونه مسدودساز uBlock Origin یا AdGuard دارید میتونید لیست PersianBlocker رو از تنظیمات افزونه فعّال کنید.

توضیحات بیشتر:
https://github.com/MasterKia/PersianBlocker
