### ISSUE TITLE
Please also add this two source for ads list

### ISSUE THREAD

**Issue by rustforfuture** [SamadiPour/iran-hosted-domains#22]
سلام
لطفا این دوتا لیست رو هم توی لیست تبلیغاتی تون به عنوان سورس برای دامنه هایی که توی لیست آقای فرخی نیستن استفاده کنید که تکمیل تر بشه

با تشکر فراوان

https://github.com/nimasaj/uBOPa

https://github.com/SlashArash/adblockfa

**Comment by SamadiPour** [comment]
سلام.
ممکن نیستش.
این لیست ها برای مرورگر هستن و نه برای این کار.

**Comment by rustforfuture** [comment]
بله درسته
سعی میکنم باهاشون صحبت کنم ببینم حاضر هستن سایتای کلیکی و اد نتورک ها رو جدا توی یه لیست قرار بدن یا نه
