### ISSUE TITLE
please add google search 

### ISSUE THREAD

**Issue by dawoodiran** [SamadiPour/iran-hosted-domains#23]
hi 
please add google search for direct  without need solve capcha
سلام اگه بشه موتور جسجوی گوگل را هم اضافه کنید تا نیاز به کپچا نباشه
به کلش اضافه کردم کار نکرد 
با تشکر

**Comment by SamadiPour** [comment]
سلام
برای این کار خودتون باید از geosite:google استفاده کنید.
این کانفیگ فقط برای سایت های ایران هستش و من اضافه نمیکنم.
