### ISSUE TITLE
False Positives for `rzb.ir` and `khf.nz`

### ISSUE THREAD

**Issue by DRSDavidSoft** [SamadiPour/iran-hosted-domains#32]
‫با عرض سلام، دامنه های زیر جزو تبلیغات نیستند:

- `rzb.ir`: ‫این دامنه، شکل کوتاه شده‌ی سرویس وبلاگدهی [رزبلاگ](https://www.rozblog.com/) می‌باشد و صرفاً جهت سرو نمودن تبلیغات استفاده نمی‌گردد.  برای دسترسی به بلاگ‌ها از طریق این دامنه، بایستی که وایت لیست شود.

- `khf.nz`: ‫این نیز دامنه CDN سرویس [خبربان](https://khabarban.com/) است، و با بلاک نمودن آن تصاویر و سایر محتوای CDN این سرویس به درستی بارگذاری نخواهد شد. البته برای سرو نمودن تبلیغات هم از همین دامنه استفاده شده، ولی همانطور که در سایت‌های دیگر (مانند تابناک) بلاک نمودن دامنه CDN موجب لود نشدن محتوای سایت می‌شود، بلاک نمودن این دامنه هم همین مشکل را ایجاد می‌کند.

‫ضمناً بنده یک لیست دامنه‌های تبلیغات را maintain می‌کنم، که کمی extensiveتر از لیست فعلی است، اگر تمایل دارید می‌توانید نگاهی بیندازید؛ با اجازه شما تعدادی از ساب‌دامین‌هایی که در لیست شما وجود داشت و یکی دو دامنه دیگر را نیز به لیست خودم merge کردم:
https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/unwanted-iranian.txt

‫با سپاس

**Comment by SamadiPour** [comment]
تشکر بابت توضیحات.
منبع دامنه های تبلیغات این ریپو، بلاک لیست آقای فرخی هستش
https://github.com/farrokhi/adblock-iran/blob/master/pihole.txt

به نظرم بهتره همکاری کنید و یک لیست جامع تری درست کنید و منم بر اساس اون لیست آپدیت میکنم.

**Comment by DRSDavidSoft** [comment]
سپاس فراوان، از بابت همکاری و تجمیع لیست بسیار خوشحال خواهم شد که تا جای ممکن بتوان به‌عنوان reference استفاده نمود و جلوی duplicate شدن نیز گرفته شود.

من دومین contributor در لیست آقای فرخی هستم:
https://github.com/farrokhi/adblock-iran/graphs/contributors

این دو مورد رو هم در upstream اشاره می‌کنم که اصلاح انجام بشه.

متشکرم
