### ISSUE TITLE
V2rayNG

### ISSUE THREAD

**Issue by Apanj** [SamadiPour/iran-hosted-domains#33]
سلام  جناب صمد پور 
آیا در V2rayNG  در اندروید هم فایل.Iran.dat را میشود استفاده کرد یا  فایل qv2ray_schema.json ?
اگر بله  آیا فقط وارد کردن فایل در  geo asset  files  کافی هست و یا باید دستورات را وارد کرد . من جایی برای وارد کردن دستورات مثل ساگرنت پیدا نکردم ! 
با تشکر از برنامه های خوب شما

**Comment by emranovin** [comment]
https://github.com/SamadiPour/iran-hosted-domains/blob/main/README.fa.md#v2rayng

> سلام جناب صمد پور
> آیا در V2rayNG در اندروید هم فایل.Iran.dat را میشود استفاده کرد یا فایل qv2ray_schema.json ?
> اگر بله آیا فقط وارد کردن فایل در geo asset files کافی هست و یا باید دستورات را وارد کرد . من جایی برای وارد کردن دستورات مثل ساگرنت پیدا نکردم !
> با تشکر از برنامه های خوب شما

https://github.com/SamadiPour/iran-hosted-domains/blob/main/README.fa.md#v2rayng
