### ISSUE TITLE
سوال ساده

### ISSUE THREAD

**Issue by shahabsaalami** [SamadiPour/iran-hosted-domains#38]
درود
من qv2ray نصب کردم و لیست دامنه های هم اضافه کردم،اما اتفاق خاصی نیفتاد!
متوجه نشدم چطوری با وی پی ان که دارم فعال بشه.
ممنون میشم راهنماییم کنید

**Comment by SamadiPour** [comment]
باید از کلاینت qv2ray به عنوان کلاینت وی پی ان استفاده کنید. برای مثال سرور شدوساکس داشته باشید و اونجا وارد کنید و استفاده کنید.
