### ISSUE TITLE
صاد.com   مشکل دارد با  switchy_omega

### ISSUE THREAD

**Issue by peymanhaji** [SamadiPour/iran-hosted-domains#41]
لطفا   com.صاد*   را از لیست switchy_omega.txt  حذف کنید.
زیرا برنامه switchy_omega   قادر به پردازش فونت فارسی نیست
و وقتی com.صاد* را در bypass list  اش قرار میدهیم برنامه فقط  * اش  را پردازش می کند و این باعث می شود که
اشتباها تمامی سایت ها بایپس شوند 

کلا بهتر است از بقیه لیست ها نیز حذف شود چون با داشتن فونت فارسی ممکن است مشکلاتی مانند این ایجاد کند

**Comment by MasterKia** [comment]
> کلا بهتر است از بقیه لیست ها نیز حذف شود 

اگه با این جایگزینش کنن مشکل حل میشه؟

`xn--mgbqq.com`

**Comment by peymanhaji** [comment]
بله درست میشه
پس خواهشا در تمامی لیستها از این به بعد جایگزین کنید ممنون

**Comment by peymanhaji** [comment]
یه خواهش دیگه اینکه https://www.aparatsport.com/  رو نیز اضافه کنید ممنون

**Comment by SamadiPour** [comment]
در ریلیز آخر، صاد حذف شد
