### ISSUE TITLE
لیست PersianBlockerHosts

### ISSUE THREAD

**Issue by MasterKia** [SamadiPour/iran-hosted-domains#43]
درود بر شما.
چندین ماهه که لیست [Adblock Iran](https://github.com/farrokhi/adblock-iran) دیگه نگهداری و بروزرسانی نمیشه،‌ بنابراین لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) ساخته شد و در افزونه های uBlock Origin و AdGuard [به جای لیست پیشین قرار گرفت](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0).

لیست [PersianBlockerHosts](https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt) (برگرفته از **PersianBlocker**) صرفاً شامل دامنه های تبلیغاتی و ردیاب (Tracker) هست و می‌تونید جایگزین [فایل ads.txt](https://raw.githubusercontent.com/SamadiPour/iran-hosted-domains/main/src/data/ads.txt) کنونی بکنیدش (به درخواست چند تا از دوستان). 

### ۱. لطفاً در GitHub Actions ترتیب اثر بدید که لیست به صورت **_خودکار_** دریافت و بروزرسانی بشه و نیاز نباشه شما به صورت "دستی" مقادیر جدید رو اضافه کنید، چون لیست [همواره در حال تغییر و بروزرسانی](https://github.com/MasterKia/PersianBlocker/commits/main/PersianBlockerHosts.txt) هست:
`wget https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt`

### ۲. لطفاً بالای فایل مربوط به لیست یا توی README ذکر کنید که لایسنس لیست AGPLv3 هستش.

با سپاس از شما.

cc @SamadiPour

**Comment by FlashWins** [comment]
> درود بر شما. چندین ماهه که لیست [Adblock Iran](https://github.com/farrokhi/adblock-iran) دیگه نگهداری و بروزرسانی نمیشه،‌ بنابراین لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) ساخته شد و در افزونه های uBlock Origin و AdGuard [به جای لیست پیشین قرار گرفت](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0).
> 
> لیست [PersianBlockerHosts](https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt) (برگرفته از **PersianBlocker**) صرفاً شامل دامنه های تبلیغاتی و ردیاب (Tracker) هست و می‌تونید جایگزین [فایل ads.txt](https://raw.githubusercontent.com/SamadiPour/iran-hosted-domains/main/src/data/ads.txt) کنونی بکنیدش (به درخواست چند تا از دوستان).
> 
> ## فقط دو مورد:
> ### ۱. لطفاً در GitHub Actions ترتیب اثر بدید که لیست به صورت **_خودکار_** دریافت و بروزرسانی بشه و نیاز نباشه شما به صورت "دستی" مقادیر جدید رو اضافه کنید، چون لیست [همواره در حال تغییر و بروزرسانی](https://github.com/MasterKia/PersianBlocker/commits/main/PersianBlockerHosts.txt) هست:
> `wget https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt`
> 
> ### ۲. لطفاً بالای فایل مربوط به لیست یا توی README ذکر کنید که لایسنس لیست AGPLv3 هستش.
> با سپاس از شما.
> 
> cc @SamadiPour

با سلام
بسیار بسیار فکر خوبی است . به جرات میتوان گفت که لیست PersianBlocker قوی ترین لیست ادبلاک فارسی است. اگر به صورت آپدیت شده در iran.dat استفاده شود تاثیر بسیار خوبی در افزایش سرعت و کاهش مصرف اینترنت خواهد داشت. 
از آقای صمدی پور خواهشمندم که در صورت امکان این امر مهم را در دستور کار قرار دهند. 

با سپاس.

**Comment by SamadiPour** [comment]
سلام.
به نظر میرسه لیست خوبی هست.
حقیقتا من علاقه ای ندارم تو این ریپو، دامنه های تبلیغاتی هم باشه.
ولی با توجه به درخواست های بسیار بسیار زیاد، من سعی میکنم شنبه یکشنبه که تعطیل هستم، پیاده سازی کنم.

**Comment by SamadiPour** [comment]
قابلیت انجامش وجود داره ولی نیاز به یه Regex قوی و بدون اشکال داره. اگر کسی وقتشو داره، انجام بده و PR بزنه. من بعد از اون بررسی میکنم.

**Comment by SamadiPour** [comment]
در حال حاضر [نسخه آخر](https://github.com/SamadiPour/iran-hosted-domains/releases/tag/202209161632) شامل دامنه های تبلیغاتی رو میتونید از ریلیز بگیرید
نیاز به تست داره برای همین فعلا issue رو نمیبندم.
خودم نمیتونم تست کنم.

به دوتا دامنه شک دارم که ممکنه مشکل ایجاد کنه:
```
10.10.34.
10.10.34.*
```

لطفا تست بشه و اطلاع بدید

**Comment by FlashWins** [comment]
> در حال حاضر [نسخه آخر](https://github.com/SamadiPour/iran-hosted-domains/releases/tag/202209161632) شامل دامنه های تبلیغاتی رو میتونید از ریلیز بگیرید نیاز به تست داره برای همین فعلا issue رو نمیبندم. خودم نمیتونم تست کنم.
> 
> به دوتا دامنه شک دارم که ممکنه مشکل ایجاد کنه:
> 
> ```
> 10.10.34.
> 10.10.34.*
> ```
> 
> لطفا تست بشه و اطلاع بدید

لیست کاملا بدون مشکل کار می کنه . با سپاس فراوان از شما 🌹🌹

**Comment by SamadiPour** [comment]
بحث برخورد نیست. بحث این هست که ممکنه منطق برنامه به خوبی نوشته نشده باشه و سعی کنه دامنه رو هندل کنه ولی دامنه معتبر نیست و به مشکل بخوره.
البته الان که میگید مشکلی نیست. اگر بعدا مشکلی بود خبر بدید.
من خودم با توجه به چیزی که استفاده میکنم، دیگه از این موارد نمیتونم استفاده کنم و قابلیت تست کردنشون رو هم ندارم.
