### ISSUE TITLE
V2RayNG

### ISSUE THREAD

**Issue by CapitanArdeshir** [SamadiPour/iran-hosted-domains#47]
سلام جناب صمدپور
ابتدا ممنون بابت این فایل و وقتی که گذاشتید، 
یک سوال داشتم در مورد برنامه V2RayNG، بنده پس از اضافه کردن فایل dat. در قسمت custom rules به سه بخش برخورد کردم، شما در توضیحات متن مورد استفاده رو محبت کردید و گذاشتید ولی نگفتید در کدوم از این 3 بخش کپی بشه. ممنون میشم شما یا دوستان دیگز بفرمایند در بخش های 
Proxy URL Or IP
Direct URL Or IP
Blocked URL Or IP
چه متن هایی به تفکیک باید نوشته شود.
تشکر

**Comment by emranovin** [comment]
https://github.com/SamadiPour/iran-hosted-domains/blob/main/README.fa.md#v2rayng
