### ISSUE TITLE
windows setup

### ISSUE THREAD

**Issue by Morteza-Gh-Kh** [SamadiPour/iran-hosted-domains#5]
Hey thanks for the great work
Any idea/hints to enable this project in windows?

**Comment by SamadiPour** [comment]
Qv2ray client supports macOS, windows and linux. You can download and install [latest version](https://github.com/Qv2ray/Qv2ray/releases) and follow [configuration guide](https://qv2ray.net/getting-started/step2.html#download-v2ray-core-files).
