### ISSUE TITLE
اضافه کردن دامین وب بله

### ISSUE THREAD

**Issue by ehsanecc** [SamadiPour/iran-hosted-domains#51]
دامین وب بله به آدرس:

web.bale.ai
در لیست نیست. در صورتی که خود دامنه اصلی دو بار تکرار شده در فایل domains.txt

**Comment by SamadiPour** [comment]
سلام.
حالت تکراری حذف شد. درحالت کلی اگر bale.ai در لیست باشه، باید web.bale.ai هم زیر مجموعه ش حساب بشه و مشکلی نباشه. بازم محض احتیاط به لیست اضافه میکنم.
