### ISSUE TITLE
remove play.googleapis.com

### ISSUE THREAD

**Issue by Airuop** [SamadiPour/iran-hosted-domains#52]
این دامنه توی iran-hosted-domains هست از clash_rules.yaml باید پاک شود
 در مواقع فیلترینگ در دانلود از پلی استور مشکل ایجاد میکند
play.googleapis.com

**Comment by SamadiPour** [comment]
سلام
تشکر. برنامه رو تغییر دادم که این دامنه رو حذف کنه.
