### ISSUE TITLE
Clash Persian Docs

### ISSUE THREAD

**Issue by gladiators1980** [SamadiPour/iran-hosted-domains#63]
how to add file in clash app?

**Comment by gladiators1980** [comment]
برای برنامه کلش هم توضیح بدید ممنون میشم

**Comment by ahbanavi** [comment]
توضیحات انگلیسی موجود هست در [اینجا](https://github.com/SamadiPour/iran-hosted-domains/blob/main/README.md#clash-like-clashx--clash_for_windows_pkg--clash-net--)


ایشو رو باز نگه‌میدارم برای اضافه کردن نسخه‌ی فارسی
