### ISSUE TITLE
playStore

### ISSUE THREAD

**Issue by matador7495** [SamadiPour/iran-hosted-domains#65]
سلام .
زمانیکه از این دیتابیس در برنامه clash for android استفاده میشه متاسفانه دانلود از پلی استور غیر ممکن میشه و به حالت pending قرار میگیره . سایر موارد مشکلی نیست

ممنون بابت تهیه این دیتابیس عالی

**Comment by SamadiPour** [comment]
Fixed in the latest release (#57bfb74)

**Comment by matador7495** [comment]
حل شده مشکل که بستید؟
