### ISSUE TITLE
add Regular expression

### ISSUE THREAD

**Issue by matador7495** [SamadiPour/iran-hosted-domains#67]
سلام امکان اضافه کردن این reg

regexp:.+\.ir$

وجود دارد تا دیگر نیاز نباشد دامنه های ir را یکی یکی معرفی کنیم و تمام دامنه ها را شامل شود.

**Comment by SamadiPour** [comment]
از خیلی قبل تو آموزش توضیح داده شده که میتونن اضافه کنن

**Comment by matador7495** [comment]
بله منظور بنده این بود در yaml برنامه clash اضافه بشه چون خیلی از سایت هایی ک *.ir هستن متاسفانه در لیست وجود نداره. اینجوری مرتب باید درخواست ثبت کنیم و آدرس های جدید را بفرستیم درواقع بجای اینکه ir ها رو اضافه کنیم این دستور اضافه بشه سپس دوستان سایر دامنه هایی ک سایت ایرانی هستن مثل com و... رو فقط ثبت کنند.
