### ISSUE TITLE
ساگرنت

### ISSUE THREAD

**Issue by FitBoy1989** [SamadiPour/iran-hosted-domains#8]
![Screenshot_20210627_181013_io nekohasekai sagernet](https://user-images.githubusercontent.com/86560861/123547615-bc49d480-d776-11eb-9230-770be99246b4.jpg)
Error میده ساگرنت

**Comment by SamadiPour** [comment]
دقیقا نمیدونم مشکل از چی هست.
برای درست شدنش میتونید یا تغییر نام بدید یا با دانلود منیجر فایل رو دانلود کنید.

**Comment by saeidk021** [comment]
من نمیتونم فایلشو دانلود کنم، شاید چون ناشی ام
یکی بفرسته ب آیدیم
@flower705
توی تل تشکر

**Comment by FitBoy1989** [comment]
سلام. جناب تشکر از اینکه تخصص تون رو به اشتراک میزارید.
برای ساگرنت. اندروید یک فایل هست؟ iran.dat درسته یاخیر؟( چون بنظرم یک other
هم هست ولی فایل رو برای دانلود پیدا نکردم) بعد امکان اینکه کاری کرداپلیکیشن
هایی مث گپ فیلم وفیلیمو نیاز به خاموش کردن  ساگرنت نداشته باشن نیست.؟ در
اندروید

**Comment by SamadiPour** [comment]
@FitBoy1989 
بله برای ساگرنت اندروید فقط به همون یک فایل نیاز دارید.
بله امکانش هست. میتونید از تنظیمات گزینه
Apps VPN mode
رو فعال کنید. سپس از نوار بالا روی گزینه
bypass
بزنید و اپ هایی که میخواین پروکسی روی آن ها اعمال نشود رو انتخاب کنید.

البته بعضی از اپ های ایرانی کلا به وصل بودنش گیر میدن و کاری به آی پی ایران ندارند (مثل اپلیکیشن بانک صادرات)

**Comment by fakhamatia** [comment]
![Screenshot_2021-07-04-17-59-05-868_io nekohasekai sagernet](https://user-images.githubusercontent.com/20030910/124386883-b06b8e80-dcf1-11eb-8b20-1c117835c34b.jpg)

من این مشکل رو دارم راه حلش چیه

**Comment by SamadiPour** [comment]
@fakhamatia 
بالاتر توضیح دادم. سعی کنید با دانلود منیجر دانلود کنید یا اسم فایل رو عوض کنید.

**Comment by fakhamatia** [comment]
> @fakhamatia
> بالاتر توضیح دادم. سعی کنید با دانلود منیجر دانلود کنید یا اسم فایل رو عوض کنید.

تغییر نام یا دانلود منیجر تاثیری نداره
