### ISSUE TITLE
V2ray Config in Iran

### ISSUE THREAD

**Issue by mmoradi15** [SamadiPour/iran-hosted-domains#9]
Hi there
I know it's not relating to this repository but I tried many configs on v2ray using port 443 but nothing work fine. I wonder to know which type of config (VLESS,VMESS , ...) do you use for v2ray?

**Comment by SamadiPour** [comment]
Hey,
Generally, v2ray-core supports Socks, HTTP, Shadowsocks, VMess etc. I like using Shadowsocks.
First of all, make sure that your proxy/server works.
You can use clients (like `qv2ray`) to make sure everything is in place and works fine.
